import type { Metadata } from "next";
import { Geist, Geist_Mono, Reddit_Sans, Mrs_Sheppards } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const redditSans = Reddit_Sans({
  variable: "--font-reddit-sans",
  subsets: ["latin"],
});

const mrsSheppards = Mrs_Sheppards({
   variable: "--font-mrs-sheppards",
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Weather Now",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${mrsSheppards.variable} ${redditSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
